### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by anthonydenecheau** [XciD/traefik-plugin-rewrite-headers#4]
See my config

```
pilot:
  token: xxxx
experimental:
  plugins:
    rewriteHeaders:
      modulename: "github.com/XciD/traefik-plugin-rewrite-headers"
      version: "v0.0.3"
```

```
http:
  routers:
     my-router:
      rule: "Host(`{{env "LOCAL_NAME"}}`) && PathPrefix(`/api`)"
      entryPoints:
      - "web"
      middlewares:
      - rewriteHeaders
      service: "my-service"

  middlewares:
    rewriteHeaders:
      plugin:
        rewriteHeaders:
          header: "Location"
          regex: "^http://{{env "LOCAL_NAME"}}/api/(.*)"
          replacement: "https://externalUrl/${1}"
          
  services:
    my-service:
      loadBalancer:
        servers:
          - url: http://{{env "LOCAL_NAME"}}  
```
